### ISSUE TITLE
Python 3 incompatibility

### ISSUE THREAD

**Issue by abompard** [puiterwijk/flask-oidc#19]
Running `oidc-discover` on Python3 can lead to a traceback:
```
ERROR:oidc-register:Error caught when discovering OP information:
Traceback (most recent call last):
  File "[...]/lib/python3.5/site-packages/flask_oidc/registration_util.py", line 65, in main
    OP = discovery.discover_OP_information(args.provider_url)
  File "[...]/lib/python3.5/site-packages/flask_oidc/discovery.py", line 43, in discover_OP_information
    return json.loads(content)
  File "/usr/lib64/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
This is because `httplib2` returns the content as bytes, not strings, and `json.loads()` expects strings. I have a patch to fix this, I'll submit a PR right now.

**Comment by abompard** [comment]
Ah, this has already been fixed in 9dfa073. Could you make a new release please?
